import React, { useState, type ReactNode } from "react";
import { Link } from "wouter";
import { dzd } from "../../client/src/core/money";
import type { Product } from "../../client/src/core/types";
import type { OwnedTemplateContract, TemplateExperience, TemplateRuntimeProps } from "../../client/src/core/templates/types";
import "./runtime.css";

const spec = {"id":"margin-bookshop","family":"editorial","navigation":"bookshop","card":"book","home":"essay","catalog":"index","product":"chapter","cart":"ledger","checkout":"chapter","links":[["Shelf","/catalog"],["Authors","/catalog?authors=1"],["Margins","/search"],["Ledger","/cart"]],"lead":"Volume","action":"Add volume","suffix":"bookshop"} as { id: string; family: string; navigation: string; card: string; home: string; catalog: string; product: string; cart: string; checkout: string; links: readonly (readonly [string, string])[]; lead: string; action: string; suffix: string };

function Brand({ config }: Pick<TemplateRuntimeProps, "config">) { return <Link href="/" className="owned-wordmark">{config.identity.logo?.url ? <img src={config.identity.logo.url} alt={config.identity.name} /> : config.identity.wordmark}</Link>; }
function CartLink({ count }: { count: number }) { return <Link href="/cart" className="owned-cart">Ledger <b>{String(count).padStart(2, "0")}</b></Link>; }
function Navigation({ mobile = false }: { mobile?: boolean }) { const [open, setOpen] = useState(!mobile); const menuId = "margin-bookshop-navigation"; return <nav className="owned-navigation" aria-label="margin-bookshop navigation"><button type="button" className="owned-nav-toggle" aria-expanded={open} aria-controls={menuId} onClick={() => setOpen(value => !value)}><span>{open ? "Close menu" : "Open menu"}</span><b aria-hidden="true">{open ? "−" : "+"}</b></button><div id={menuId} className="owned-nav-links" hidden={mobile && !open}>{spec.links.map(([label, href], index) => <Link key={label} href={href}><i>{String(index + 1).padStart(2, "0")}</i><span>{label}</span></Link>)}</div></nav>; }
function Footer({ config }: Pick<TemplateRuntimeProps, "config">) { return <footer className="owned-footer"><span>{config.identity.footerText}</span><span>{config.business.email}</span><span>margin-bookshop-owned</span></footer>; }
function Frame({ props, children }: { props: TemplateRuntimeProps; children: ReactNode }) { return <div className="owned-frame owned-editorial"><aside className="owned-rail"><Brand config={props.config} /><Navigation mobile={props.device === "mobile"} /><CartLink count={props.cart.reduce((sum, item) => sum + item.quantity, 0)} /></aside><div className="owned-main">{props.has("announcement-bar") && <p className="owned-announcement">Algeria delivery · all prices in DZD</p>}<div className="owned-content">{children}</div><Footer config={props.config} /></div></div>; }
function Heading({ eyebrow, title, count }: { eyebrow: string; title: string; count?: number }) { return <header className="owned-heading" data-page-system={spec.catalog}><p>{eyebrow}</p><h1>{title}</h1><span>{count === undefined ? spec.suffix : String(count).padStart(2, "0") + " / " + spec.suffix}</span></header>; }
function Card({ product, index, props }: { product: Product; index: number; props: TemplateRuntimeProps }) { return <article className="owned-card owned-card-editorial" data-card-system="book"><span className="owned-card-index">{String(index + 1).padStart(2, "0")}</span><button className="owned-card-media" onClick={() => props.navigate("/product/" + product.slug)}><img src={product.image} alt="" /></button><div className="owned-card-copy"><p>Volume / {product.category}</p><h3>{product.name}</h3><strong>{dzd(product.priceDzd)}</strong><button onClick={() => props.add(product)}>Add volume →</button></div></article>; }
function Home({ props }: { props: TemplateRuntimeProps }) { const Extra = props.TemplateComposition; const take = spec.home === "singular" ? 1 : spec.family === "market" || spec.family === "pantry" ? 6 : 4; return <main className="owned-page owned-home" data-home-system={spec.home}><section className="owned-hero owned-hero-editorial"><div><p>bookshop / DZD storefront</p><h1>{props.config.identity.heroTitle}</h1><p>{props.config.identity.heroText}</p><button onClick={() => props.navigate("/catalog")}>{props.config.identity.heroCta}</button></div><aside><span>bookshop / issue 01</span><img src={props.config.identity.heroImage || props.featured.image} alt="" /><span>Annotated daily objects</span></aside></section>{Extra && <Extra template={props.template} product={props.featured} />}<section className="owned-collection"><Heading eyebrow="Selected objects" title={spec.family === "market" ? "Ready for today" : spec.family === "technical" ? "Useful systems" : "A considered edit"} /><div className="owned-grid">{props.config.catalog.slice(0, take).map((product, index) => <Card key={product.id} product={product} index={index} props={props} />)}</div></section></main>; }
function Catalog({ props, searchOnly = false }: { props: TemplateRuntimeProps; searchOnly?: boolean }) { const products = props.filtered; const title = searchOnly ? "Search, then narrow" : spec.family === "market" ? "Trade floor" : spec.family === "technical" ? "Equipment index" : spec.family === "pantry" ? "The pantry shelf" : "Everything, arranged"; return <main className="owned-page owned-catalog" data-catalog-system={spec.catalog}><Heading eyebrow={searchOnly ? "Find an object" : "The catalog"} title={title} count={products.length} /><div className="owned-tools"><label><span>Search</span><input value={props.query} onChange={event => props.setQuery(event.target.value)} placeholder={spec.family === "technical" ? "Search specifications" : "Search products and categories"} /></label><div><button>All categories</button><button>{spec.family === "market" ? "Ready today" : "Available now"}</button><button>{spec.card} view</button></div></div>{products.length ? <div className="owned-grid">{products.map((product, index) => <Card key={product.id} product={product} index={index} props={props} />)}</div> : <SimplePage props={props} kind="empty" />}</main>; }
function ProductPage({ props }: { props: TemplateRuntimeProps }) { const product = props.currentProduct; const [option, setOption] = useState(product.options[0]?.values[0] ?? "Standard"); const [activeImage, setActiveImage] = useState(0); const images = product.images.length ? product.images : [product.image]; const selected = images[activeImage] ?? images[0]; return <main className="owned-page owned-product" data-product-system={spec.product}><section className="owned-gallery"><div className="owned-product-media"><img src={selected} alt={product.name + " view " + (activeImage + 1)} /><span>chapter · {activeImage + 1}/{images.length}</span></div>{images.length > 1 && <div className="owned-thumbnails" aria-label={product.name + " image gallery"}>{images.map((image, index) => <button key={image + index} className={activeImage === index ? "active" : ""} onClick={() => setActiveImage(index)} aria-label={"View image " + (index + 1)}><img src={image} alt="" /></button>)}</div>}</section><section className="owned-product-detail"><p>bookshop / In stock</p><h1>{product.name}</h1><strong>{dzd(product.priceDzd)}</strong><p>{product.description}</p>{product.options.map(group => <fieldset key={group.name}><legend>{group.name}</legend><div>{group.values.map(value => <button key={value} className={option === value ? "selected" : ""} onClick={() => setOption(value)}>{value}</button>)}</div></fieldset>)}<button className="owned-primary" onClick={() => { props.add(product, option); props.navigate("/cart"); }}>Add volume · {dzd(product.priceDzd)}</button>{props.has("size-guide") && <p className="owned-detail-row">Need a size? Consult the size guide before ordering.</p>}{props.has("product-faq") && <details><summary>Product questions</summary><p>This preview uses deterministic catalog data; the export contains the selected plugin module.</p></details>}<p className="owned-detail-row">Algerian delivery and payment choices are shown at checkout.</p></section></main>; }
function Cart({ props }: { props: TemplateRuntimeProps }) { if (!props.cart.length) return <SimplePage props={props} kind="empty" />; const fee = props.config.operations.deliveryMethods[0]?.feeDzd ?? 0; return <main className="owned-page owned-cart" data-cart-system={spec.cart}><section><p>ledger / your selection</p><h1>Selected with intent.</h1>{props.cart.map(item => <article className="owned-cart-item" key={item.product.id + item.option}><img src={item.product.image} alt="" /><div><h2>{item.product.name}</h2><p>{item.option}</p><strong>{dzd(item.product.priceDzd)}</strong></div><div className="owned-quantity"><button onClick={() => props.changeQuantity(item.product.id, item.quantity - 1)}>−</button><span>{item.quantity}</span><button onClick={() => props.changeQuantity(item.product.id, item.quantity + 1)}>+</button></div></article>)}</section><aside className="owned-summary"><p>Selection ledger</p><div><span>Objects</span><strong>{dzd(props.total)}</strong></div><div><span>{props.config.operations.deliveryMethods[0]?.label ?? "Delivery"}</span><strong>{dzd(fee)}</strong></div>{props.has("gift-note") && <label>Gift note<textarea placeholder="A short note for the recipient" /></label>}<div className="owned-total"><span>Total</span><strong>{dzd(props.total + fee)}</strong></div><button className="owned-primary" onClick={() => props.navigate("/checkout")}>Continue to checkout</button></aside></main>; }
function Checkout({ props }: { props: TemplateRuntimeProps }) {
  const [payment, setPayment] = useState(props.config.operations.paymentMethods[0] ?? "Cash on delivery");
  const [delivery, setDelivery] = useState(props.config.operations.deliveryMethods[0]?.id ?? "home");
  const [customerName, setCustomerName] = useState("");
  const [phone, setPhone] = useState("");
  const [address, setAddress] = useState("");
  const [status, setStatus] = useState<"idle" | "submitting" | "error">("idle");
  const [error, setError] = useState("");
  if (!props.cart.length) return <SimplePage props={props} kind="empty" />;
  const submit = async (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    setStatus("submitting"); setError("");
    try { await props.placeOrder({ customerName, phone, address, deliveryId: delivery, paymentMethod: payment }); props.navigate("/success"); }
    catch (cause) { setStatus("error"); setError(cause instanceof Error ? cause.message.replaceAll("_", " ") : "CHECKOUT FAILED"); }
  };
  return <main className="owned-page owned-checkout" data-checkout-system={spec.checkout}><form id="margin-bookshop-checkout" onSubmit={submit}><p>{spec.checkout} / DZD</p><h1>{spec.family === "market" || spec.family === "pantry" ? "Choose delivery." : spec.checkout === "express" ? "Finish quickly." : "Where should we send it?"}</h1><div className="owned-form"><label>Full name<input value={customerName} onChange={event => setCustomerName(event.target.value)} placeholder="Your full name" autoComplete="name" required /></label><label>Phone<input value={phone} onChange={event => setPhone(event.target.value)} placeholder="0550 00 00 00" autoComplete="tel" inputMode="tel" required /></label><label>Address<input value={address} onChange={event => setAddress(event.target.value)} placeholder="Street, district, wilaya" autoComplete="street-address" required /></label></div><h2>Delivery method</h2>{props.config.operations.deliveryMethods.map(method => <label className="owned-choice" key={method.id}><input type="radio" checked={delivery === method.id} onChange={() => setDelivery(method.id)} /><span>{method.label} · {dzd(method.feeDzd)}</span></label>)}<h2>Payment</h2>{props.config.operations.paymentMethods.map(method => <label className="owned-choice" key={method}><input type="radio" checked={payment === method} onChange={() => setPayment(method)} /><span>{method}</span></label>)}</form><aside className="owned-summary"><p>{spec.checkout} payment</p><h2>{dzd(props.total + (props.config.operations.deliveryMethods.find(method => method.id === delivery)?.feeDzd ?? 0))}</h2><p>Prices and inventory are verified on the server before this order is accepted.</p>{status === "error" && <p role="alert" className="owned-checkout-error">{error}</p>}<button className="owned-primary" type="submit" form="margin-bookshop-checkout" disabled={status === "submitting"}>{status === "submitting" ? "Placing secure order…" : "Place order"}</button></aside></main>; }

function SimplePage({ props, kind }: { props: TemplateRuntimeProps; kind: "tracking" | "success" | "empty" | "not-found" | "login" | "register" }) { const [submitted, setSubmitted] = useState(false); if (kind === "login" || kind === "register") return <main className="owned-page owned-auth"><section><p>Preview-only {kind}</p><h1>{kind === "login" ? "Welcome back." : "Create your preview account."}</h1><p>These fields demonstrate the final design. They do not create an account or authenticate a user.</p></section><form onSubmit={event => { event.preventDefault(); setSubmitted(true); }}><label>Email<input type="email" placeholder="you@example.com" /></label><label>Password<input type="password" placeholder="••••••••" /></label>{kind === "register" && <label>Full name<input placeholder="Your name" /></label>}<button className="owned-primary" type="submit">{kind === "login" ? "Preview sign in" : "Preview registration"}</button>{submitted && <p>Preview complete — no real session was created.</p>}<button type="button" onClick={() => props.navigate("/")}>Return to store</button></form></main>; const copy = kind === "tracking" ? ["Order tracking", "Order DZ-2026-0148", "Your deterministic preview order is being prepared in Algiers."] : kind === "success" ? ["Order confirmed", "Thank you. It is on its way.", "In the export, this page receives the response from the independent Express order endpoint."] : kind === "not-found" ? ["404 / Lost page", "This route has no object.", "Return to the catalog to keep exploring."] : ["Nothing here yet", "Your bag is waiting for an object.", "Browse the catalog to begin a selection."]; return <main className="owned-page owned-simple"><p>{copy[0]}</p><h1>{copy[1]}</h1>{kind === "tracking" && <div className="owned-tracking"><span>Order confirmed</span><span>Preparing</span><span>With courier</span><span>Delivered</span></div>}<p>{copy[2]}</p><button className="owned-primary" onClick={() => props.navigate(kind === "success" ? "/tracking" : kind === "tracking" ? "/catalog" : "/catalog")}>{kind === "success" ? "Track order" : "Browse catalog"}</button></main>; }
export function Runtime(props: TemplateRuntimeProps) { let page; if (props.page === "home") page = <Home props={props} />; else if (props.page === "catalog") page = <Catalog props={props} />; else if (props.page === "search") page = <Catalog props={props} searchOnly />; else if (props.page === "product") page = <ProductPage props={props} />; else if (props.page === "cart") page = <Cart props={props} />; else if (props.page === "checkout") page = <Checkout props={props} />; else page = <SimplePage props={props} kind={props.page === "login" || props.page === "register" || props.page === "tracking" || props.page === "success" || props.page === "empty" ? props.page : "not-found"} />; return <section className={"owned-device device-" + props.device} data-owned-template="margin-bookshop-owned" data-device-contract={"margin-bookshop-owned:" + props.device}><Frame props={props}>{page}</Frame></section>; }
const contract: OwnedTemplateContract = { marker: "margin-bookshop-owned", family: "editorial", devices: { desktop: "margin-bookshop-owned:desktop", tablet: "margin-bookshop-owned:tablet", mobile: "margin-bookshop-owned:mobile" }, experience: { id: "margin-bookshop", navigation: "bookshop", card: "book", home: "essay", catalog: "index", product: "chapter", cart: "ledger", checkout: "chapter" } as TemplateExperience, Runtime };
export default contract;
